// Generated by scripts/generate-api-types.mjs from docs/openapi.yaml.
// Do not edit manually.

export type RPCCode =
  | 'OK'
  | 'ACCEPTED'
  | 'AUTH_REQUIRED'
  | 'AUTH_INVALID_CREDENTIALS'
  | 'INVALID_ARGUMENT'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'OPERATION_LOCKED'
  | 'UNSUPPORTED_ACTION'
  | 'INTERNAL_ERROR'
  | 'UPSTREAM_ERROR'
  | 'SERVICE_UNAVAILABLE'
  | 'SERVER_OFFLINE'
  | 'PORT_OUT_OF_RANGE'
  | 'UPDATE_IN_PROGRESS'

export interface RPCEnvelope<T = unknown> {
  code: RPCCode
  message: string
  data: T
  request_id: string
  trace_id: string
}

export const rpcOperations = {
  authLogin: { method: 'POST', path: '/api/auth/login' },
  authLogout: { method: 'POST', path: '/api/auth/logout' },
  authMe: { method: 'GET', path: '/api/auth/me' },
  dashboardGet: { method: 'GET', path: '/api/dashboard/get' },
  serverList: { method: 'GET', path: '/api/server/list' },
  serverListMetricSamples: { method: 'GET', path: '/api/server/list-metric-samples' },
  serverGetMetricHistory: { method: 'GET', path: '/api/server/get-metric-history' },
  serverListCommands: { method: 'GET', path: '/api/server/list-commands' },
  serverCreate: { method: 'POST', path: '/api/server/create' },
  serverUpdate: { method: 'POST', path: '/api/server/update' },
  serverConfirmRenewal: { method: 'POST', path: '/api/server/confirm-renewal' },
  serverDelete: { method: 'POST', path: '/api/server/delete' },
  serverRotateToken: { method: 'POST', path: '/api/server/rotate-token' },
  serverRepair: { method: 'POST', path: '/api/server/repair' },
  serverUpgradeXray: { method: 'POST', path: '/api/server/upgrade-xray' },
  serverUpgradeAgent: { method: 'POST', path: '/api/server/upgrade-agent' },
  serverListReleaseVersions: { method: 'GET', path: '/api/server/list-release-versions' },
  providerList: { method: 'GET', path: '/api/provider/list' },
  providerCreate: { method: 'POST', path: '/api/provider/create' },
  providerUpdate: { method: 'POST', path: '/api/provider/update' },
  providerDelete: { method: 'POST', path: '/api/provider/delete' },
  exchangeRateList: { method: 'GET', path: '/api/exchange-rate/list' },
  exchangeRateRefresh: { method: 'POST', path: '/api/exchange-rate/refresh' },
  exchangeRateSaveCustom: { method: 'POST', path: '/api/exchange-rate/save-custom' },
  exchangeRateDeleteCustom: { method: 'POST', path: '/api/exchange-rate/delete-custom' },
  nodeList: { method: 'GET', path: '/api/node/list' },
  nodeCreate: { method: 'POST', path: '/api/node/create' },
  nodeRetry: { method: 'POST', path: '/api/node/retry' },
  nodeDelete: { method: 'POST', path: '/api/node/delete' },
  chainList: { method: 'GET', path: '/api/chain/list' },
  chainCreate: { method: 'POST', path: '/api/chain/create' },
  chainRetry: { method: 'POST', path: '/api/chain/retry' },
  chainDelete: { method: 'POST', path: '/api/chain/delete' },
  userList: { method: 'GET', path: '/api/user/list' },
  userCreate: { method: 'POST', path: '/api/user/create' },
  userUpdate: { method: 'POST', path: '/api/user/update' },
  userSetNodes: { method: 'POST', path: '/api/user/set-nodes' },
  userDelete: { method: 'POST', path: '/api/user/delete' },
  settingGet: { method: 'GET', path: '/api/setting/get' },
  settingUpdate: { method: 'POST', path: '/api/setting/update' },
  settingChangePassword: { method: 'POST', path: '/api/setting/change-password' },
  settingTestAlerts: { method: 'POST', path: '/api/setting/test-alerts' },
  panelRestart: { method: 'POST', path: '/api/panel/restart' },
  panelGetVersion: { method: 'GET', path: '/api/panel/get-version' },
  panelStartUpdate: { method: 'POST', path: '/api/panel/start-update' },
  panelGetUpdateStatus: { method: 'GET', path: '/api/panel/get-update-status' },
  backupDownload: { method: 'GET', path: '/api/backup/download' },
  logListOperations: { method: 'GET', path: '/api/log/list-operations' },
  logClearOperations: { method: 'POST', path: '/api/log/clear-operations' },
  logListRequests: { method: 'GET', path: '/api/log/list-requests' },
  logClearRequests: { method: 'POST', path: '/api/log/clear-requests' },
} as const
