package sub

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http/httptest"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"lattix/backend/internal/store"
)

var subscriptionFormats = []string{"clash", "singbox", "quanx", "quanx-config", "links"}

type PublishResult struct {
	store.SubscriptionSnapshotStatus
	Files    map[string][]byte `json:"files,omitempty"`
	Warnings []string          `json:"warnings,omitempty"`
}

func (s *Server) PublishUser(ctx context.Context, userID int64, baseURL string) (PublishResult, error) {
	s.rememberBaseURL(baseURL)
	lock := s.publishLock(userID)
	lock.Lock()
	defer lock.Unlock()
	user, err := s.st.UserByID(ctx, userID)
	if err != nil {
		return PublishResult{}, err
	}
	profile, err := s.st.UserSubscriptionProfile(ctx, userID)
	if err != nil {
		return PublishResult{}, err
	}
	profile = store.EffectiveProfile(profile)
	policy, sourceLabel, template, err := s.resolvePolicy(ctx, profile)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	items, chainWarnings, err := s.itemsForUser(ctx, user)
	if err != nil {
		return PublishResult{}, err
	}
	if user.Expired || user.Disabled {
		items = nil
	}
	nodes, compileWarnings, err := s.compileNodes(ctx, items, user.UUID)
	if err != nil {
		return PublishResult{}, err
	}
	panelShort := s.panelShort(ctx)
	warnings := append(append([]string{}, chainWarnings...), compileWarnings...)
	policyWarnings, err := expandPolicy(&policy, nodes, panelShort)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	warnings = append(warnings, policyWarnings...)
	if len(warnings) > 0 {
		log.Printf("sub: publish user %d (%s): %d item(s) skipped: %s",
			user.ID, user.Name, len(warnings), strings.Join(warnings, "; "))
	}
	cachedRules, err := s.cachedTemplateRules(ctx, template, policy)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	ruleFiles, err := buildRuleArtifacts(cachedRules)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	mihomoPolicy, err := rewriteRemoteRuleURLs(policy, cachedRules, "mihomo", baseURL, user.SubToken)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	singboxPolicy, err := rewriteRemoteRuleURLs(policy, cachedRules, "singbox", baseURL, user.SubToken)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	quanxPolicy, err := rewriteRemoteRuleURLs(policy, cachedRules, "quanx", baseURL, user.SubToken)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}

	files := make(map[string]store.SubscriptionFile, 2*len(subscriptionFormats))
	visible := make(map[string][]byte, len(subscriptionFormats))
	// addPre 落盘预编译中间态（<format>-pre）：仅供面板调试预览，不进入交付
	// 文件集，公共订阅端点的格式白名单也不会匹配到它。
	addPre := func(format, contentType string, content []byte, err error) error {
		if err != nil {
			return fmt.Errorf("generate %s pre-compiled: %w", format, err)
		}
		files[format+"-pre"] = store.SubscriptionFile{Format: format + "-pre", ContentType: contentType, Content: content}
		return nil
	}
	add := func(format, contentType string, content []byte, err error) error {
		if err != nil {
			return fmt.Errorf("generate %s: %w", format, err)
		}
		// 交付内容不得残留预编译占位符（残留 = 解压环节遗漏）。
		if err := assertNoPrecompiledPlaceholders(format, content); err != nil {
			return err
		}
		files[format] = store.SubscriptionFile{Format: format, ContentType: contentType, Content: content}
		visible[format] = content
		return nil
	}
	mihomoPreDoc := renderMihomoPre(mihomoPolicy)
	mihomoBody, renderErr := yaml.Marshal(mihomoPreDoc.expand(nodes))
	if renderErr == nil {
		renderErr = assertNoPrecompiledPlaceholders("clash", mihomoBody)
	}
	if renderErr == nil {
		mihomoBody = append([]byte("# Generated by Lattix. Template source and license are recorded in the panel.\n"), mihomoBody...)
	}
	if err := add("clash", "text/yaml; charset=utf-8", mihomoBody, renderErr); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	mihomoPreBytes, preErr := mihomoPreDoc.artifact()
	if err := addPre("clash", "text/yaml; charset=utf-8", mihomoPreBytes, preErr); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	singboxPreDoc := renderSingboxPre(singboxPolicy)
	content, renderErr := json.MarshalIndent(singboxPreDoc.expand(nodes), "", "  ")
	if err := add("singbox", "application/json; charset=utf-8", content, renderErr); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	singboxPreBytes, preErr := singboxPreDoc.artifact()
	if err := addPre("singbox", "application/json; charset=utf-8", singboxPreBytes, preErr); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	if err := add("quanx", "text/plain; charset=utf-8", []byte(renderQuanXNodes(nodes)), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	if err := addPre("quanx", "text/plain; charset=utf-8", []byte(renderQuanXNodesPre()), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	quanxConfigPreDoc := renderQuanXConfigPre(quanxPolicy)
	if err := add("quanx-config", "text/plain; charset=utf-8", quanxConfigPreDoc.expand(nodes), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	if err := addPre("quanx-config", "text/plain; charset=utf-8", quanxConfigPreDoc.artifact(), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	linksPreDoc := renderLinksPre(items, user.UUID)
	if err := add("links", "text/plain; charset=utf-8", linksPreDoc.expand(), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	if err := addPre("links", "text/plain; charset=utf-8", linksPreDoc.artifact(), nil); err != nil {
		return s.publishFailure(ctx, userID, err)
	}

	// Native templates replace only their matching renderer. Other formats keep
	// the portable policy output from the same snapshot.
	sourceSHA := snapshotSourceSHA(policy, cachedRules)
	for _, override := range []struct{ format, templateID string }{
		{"clash", profile.MihomoTemplateID},
		{"singbox", profile.SingboxTemplateID},
		{"quanx-config", profile.QuanXTemplateID},
	} {
		format, templateID := override.format, override.templateID
		if templateID == "" {
			continue
		}
		template, templateErr := s.st.SubscriptionTemplateByID(ctx, templateID)
		if templateErr != nil {
			return s.publishFailure(ctx, userID, fmt.Errorf("load native template %s: %w", templateID, templateErr))
		}
		nativePolicy := mihomoPolicy
		if format == "singbox" {
			nativePolicy = singboxPolicy
		} else if format == "quanx-config" {
			nativePolicy = quanxPolicy
		}
		preContent, finalContent, templateErr := applyNativeTemplateFull(format, template.Content, nativePolicy, nodes, panelShort)
		if templateErr != nil {
			return s.publishFailure(ctx, userID, templateErr)
		}
		if templateErr = assertNoPrecompiledPlaceholders(format, finalContent); templateErr != nil {
			return s.publishFailure(ctx, userID, templateErr)
		}
		file := files[format]
		file.Content = finalContent
		files[format] = file
		visible[format] = finalContent
		preFile := files[format+"-pre"]
		preFile.Content = preContent
		files[format+"-pre"] = preFile
		sourceSHA = contentSHA(sourceSHA + "\n" + format + ":" + template.ContentSHA256)
	}

	status, err := s.st.PublishSubscriptionSnapshot(ctx, userID, sourceLabel, sourceSHA, files, ruleFiles, warnings)
	if err != nil {
		return s.publishFailure(ctx, userID, err)
	}
	return PublishResult{SubscriptionSnapshotStatus: status, Files: visible, Warnings: warnings}, nil
}

func (s *Server) publishFailure(ctx context.Context, userID int64, err error) (PublishResult, error) {
	_ = s.st.SetSubscriptionGenerationError(ctx, userID, err.Error())
	return PublishResult{}, err
}

// panelShort 读取面板缩写设置（读取失败按未设置处理，回退默认值）。
func (s *Server) panelShort(ctx context.Context) string {
	raw, _ := s.st.GetSetting(ctx, store.SettingPanelShort)
	return store.EffectivePanelShort(raw)
}

func (s *Server) resolvePolicy(ctx context.Context, profile store.SubscriptionProfile) (portablePolicy, string, *store.SubscriptionTemplate, error) {
	if profile.Mode != store.SubscriptionModeTemplate {
		var selected []string
		if err := json.Unmarshal([]byte(profile.CategoriesJSON), &selected); err != nil {
			selected = append([]string(nil), presetCategories[profile.Preset]...)
		}
		policy, err := suggestedPolicy(sortedSelectedCategories(selected))
		return policy, "内置建议规则", nil, err
	}
	if profile.PortableTemplateID == "" {
		return portablePolicy{}, "", nil, errors.New("custom template mode requires a portable template")
	}
	template, err := s.st.SubscriptionTemplateByID(ctx, profile.PortableTemplateID)
	if err != nil {
		return portablePolicy{}, "", nil, err
	}
	switch template.Kind {
	case "portable":
		policy, err := parsePortablePolicy(template.Content)
		return policy, template.Name, &template, err
	case "acl4ssr":
		policy, err := parseACL4SSR(template.Content)
		return policy, template.Name, &template, err
	default:
		return portablePolicy{}, "", nil, fmt.Errorf("template %s is not portable", template.Name)
	}
}

func (s *Server) itemsForUser(ctx context.Context, user *store.User) ([]proxyItem, []string, error) {
	r := httptest.NewRequest("GET", "http://lattix.invalid/sub/compile", nil).WithContext(ctx)
	nodes, err := s.st.ListNodes(ctx)
	if err != nil {
		return nil, nil, err
	}
	active := []store.Node{}
	// 分组用户的直连 user_nodes 被遮蔽：订阅 = 分组派生链路 + 外部订阅节点。
	groupIDs, err := s.st.UserGroupIDsForUser(ctx, user.ID)
	if err != nil {
		return nil, nil, err
	}
	if len(groupIDs) == 0 {
		assigned, err := s.st.UserNodeIDs(ctx, user.ID)
		if err != nil {
			return nil, nil, err
		}
		allowed := make(map[int64]bool, len(assigned))
		for _, id := range assigned {
			allowed[id] = true
		}
		active = make([]store.Node, 0, len(assigned))
		for _, node := range nodes {
			if allowed[node.ID] && node.Status == store.NodeStatusActive && len(node.RealizedConfig) > 0 {
				active = append(active, node)
			}
		}
	}
	items, warnings := s.subscriptionItems(r, user, active)
	return items, warnings, nil
}

type compiledNode struct {
	Name        string
	CountryCode string
	Group       string // 来源分组名：面板管理节点为空，外部订阅节点为其订阅名称
	Clash       clashProxy
	Singbox     any // 面板节点为 sbOutbound；外部节点为 map[string]any
	QuanX       string
}

func (s *Server) compileNodes(ctx context.Context, items []proxyItem, uuid string) ([]compiledNode, []string, error) {
	out := make([]compiledNode, 0, len(items))
	var warnings []string
	for _, item := range items {
		if item.external != nil {
			clash, err := buildExternalClash(*item.external)
			if err != nil {
				warnings = append(warnings, err.Error())
				continue
			}
			singbox, err := buildExternalSingbox(*item.external)
			if err != nil {
				warnings = append(warnings, err.Error())
			}
			out = append(out, compiledNode{
				Name: clash.Name, CountryCode: inferNodeCountry(clash.Name), // 与面板节点同级参与区域分组
				Group: item.group, // 来源分组：外部订阅名
				Clash: clash, Singbox: singbox, // 失败时 nil，renderSingbox 跳过
				QuanX: buildExternalQuanX(*item.external),
			})
			continue
		}
		credential := item.credential
		if credential == "" {
			credential = uuid
		}
		clash, err := buildProxy(item.node, item.rc, credential)
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("节点「%s」构造 clash 代理失败：%v", item.node.Name, err))
			continue
		}
		singbox, err := buildSbOutbound(item.node, item.rc, credential)
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("节点「%s」构造 sing-box 出站失败：%v", item.node.Name, err))
			continue
		}
		country := ""
		if server, serverErr := s.st.ServerByID(ctx, item.node.ServerID); serverErr == nil {
			country = strings.ToUpper(server.CountryCode)
		}
		out = append(out, compiledNode{
			Name: clash.Name, CountryCode: country, Clash: clash, Singbox: singbox,
			QuanX: buildQuanXLine(item.node, item.rc, credential),
		})
	}
	return out, warnings, nil
}

func expandPolicy(policy *portablePolicy, nodes []compiledNode, panelShort string) ([]string, error) {
	// 模板自带分组数与地区组/节点池组标记须在追加自动生成分组前捕获。
	templateCount := len(policy.Groups)
	regionLike := make([]bool, templateCount) // 选项全部为 __LATTIX_REGION*__ 占位符的模板组 = 地区组
	poolGroup := make([]bool, templateCount)  // 选项含 __LATTIX_ALL__ 的节点池组（自动选择/故障转移等）
	firstAll, autoName := "", ""              // 「自动选择」：选项含 __LATTIX_ALL__ 的组，url-test 优先
	for i, group := range policy.Groups {
		regionLike[i] = len(group.Options) > 0
		hasAll := false
		for _, option := range group.Options {
			if !strings.HasPrefix(option, "__LATTIX_REGION") {
				regionLike[i] = false
			}
			if option == "__LATTIX_ALL__" {
				hasAll = true
			}
		}
		poolGroup[i] = hasAll
		if hasAll {
			if firstAll == "" {
				firstAll = group.Name
			}
			if autoName == "" && group.Type == "url-test" {
				autoName = group.Name
			}
		}
	}
	if autoName == "" {
		autoName = firstAll
	}
	all := make([]string, 0, len(nodes))
	byCountry := map[string][]string{}
	var noRegion []string
	for _, node := range nodes {
		all = append(all, node.Name)
		if node.CountryCode != "" {
			byCountry[node.CountryCode] = append(byCountry[node.CountryCode], node.Name)
		} else {
			noRegion = append(noRegion, node.Name)
		}
	}
	countries := make([]string, 0, len(byCountry))
	for country := range byCountry {
		countries = append(countries, country)
	}
	sort.Strings(countries)
	// 叶子分组：只含节点、不含其他组引用的分组（来源分组 + 地区分组 + 无地区分组）。
	// 它们与 __LATTIX_REGIONS__ 一同展开、一同剔除，且是节点池组唯一允许保留的组引用。
	leafGroups := make([]string, 0, len(countries)+2)
	var warnings []string
	existing := make(map[string]bool, len(policy.Groups))
	for _, group := range policy.Groups {
		existing[group.Name] = true
	}
	// 按来源分组：「<panelShort> 分组」含全部面板管理节点，每个外部订阅一组
	// （组名 = 订阅名）含其解析节点；与既有组重名时跳过，避免非法的重复组名。
	for _, group := range sourcePolicyGroups(nodes, panelShort) {
		if existing[group.Name] {
			warnings = append(warnings, fmt.Sprintf("来源分组「%s」与既有策略组重名，已跳过自动生成", group.Name))
			continue
		}
		existing[group.Name] = true
		leafGroups = append(leafGroups, group.Name)
		policy.Groups = append(policy.Groups, group)
	}
	for _, country := range countries {
		name := countryFlag(country) + " " + country
		leafGroups = append(leafGroups, name)
		policy.Groups = append(policy.Groups, policyGroup{Name: name, Type: "select", Options: []string{placeholderRegionPrefix + country + "__"}})
	}
	// 无地区标识的节点（如名称无法推断国家的外部订阅节点）收进固定的无地区分组，
	// 随 __LATTIX_REGIONS__ 一起展开，保证所有节点在分组层都可达。
	if len(noRegion) > 0 {
		leafGroups = append(leafGroups, noRegionGroupName)
		policy.Groups = append(policy.Groups, policyGroup{Name: noRegionGroupName, Type: "select", Options: []string{placeholderRegionNone}})
	}
	// 选项级占位符（__LATTIX_ALL__ / __LATTIX_REGIONS__ / __LATTIX_REGION_*__）
	// 在中间态保持原样，到最终渲染阶段才按 expansion 解析为节点/分组名字；
	// 剪枝与环检测因此必须是占位符感知的（见 pruneEmptyGroups）。
	policy.expansion = &policyExpansion{all: all, byCountry: byCountry, noRegion: noRegion, leafGroups: leafGroups}
	// 可达性增强：模板定义的分组（地区组与自动生成的来源/地区分组除外）在保留原有
	// 选项（含叶子分组引用）的基础上补充 DIRECT/REJECT 兜底并追加全部节点、
	// 「自动选择」与「节点选择」（final）引用，使任何分流组既可指定固定节点
	// 也可回落自动选择、直连或拒绝。「自动选择」自身不补 DIRECT/REJECT
	// （纯节点测速组，兜底出站会污染延迟测试结果），但追加「节点选择」引用，
	// 使客户端可把自动选择手动固定到节点选择、进而强制全部分流走统一节点。
	// 不变量：节点池组（选项含 __LATTIX_ALL__，如自动选择/故障转移）与节点选择的
	// 选项只保留节点、叶子分组与选项级占位符（及 DIRECT/REJECT），剔除其他组引用
	// ——它们因此永不反向引用分流组；「节点选择」同样被剔除组引用，故「自动选择」
	// 对它的引用不会成环，detectGroupCycle 兜底。
	finalName := ""
	if policy.Final != "DIRECT" && policy.Final != "REJECT" && existing[policy.Final] {
		finalName = policy.Final
	}
	nodeSet := make(map[string]bool, len(all))
	for _, name := range all {
		nodeSet[name] = true
	}
	leafSet := make(map[string]bool, len(leafGroups))
	for _, name := range leafGroups {
		leafSet[name] = true
	}
	// appendDirectReject 为组补充缺失的 DIRECT/REJECT 兜底选项（DIRECT 在前）。
	appendDirectReject := func(options []string) []string {
		hasDirect, hasReject := false, false
		for _, option := range options {
			if option == "DIRECT" {
				hasDirect = true
			}
			if option == "REJECT" {
				hasReject = true
			}
		}
		if !hasDirect {
			options = append(options, "DIRECT")
		}
		if !hasReject {
			options = append(options, "REJECT")
		}
		return options
	}
	for index := range policy.Groups[:templateCount] {
		if regionLike[index] {
			continue
		}
		group := &policy.Groups[index]
		options := append([]string{}, group.Options...)
		if poolGroup[index] || group.Name == finalName {
			kept := make([]string, 0, len(options))
			hasAll := false
			for _, option := range options {
				// 「自动选择」额外保留对「节点选择」（final）的引用：节点选择经
				// 同样的剥离后只剩节点/叶子分组/占位符，引用它不会成环。
				if option == "DIRECT" || option == "REJECT" || nodeSet[option] || leafSet[option] || isOptionPlaceholder(option) ||
					(group.Name == autoName && option == finalName && finalName != group.Name) {
					if option == placeholderAllNodes {
						hasAll = true
					}
					kept = append(kept, option)
				}
			}
			if group.Name != autoName {
				kept = appendDirectReject(kept)
			}
			if !hasAll {
				// 保证节点池组/final 组始终覆盖全部节点（占位符，最终渲染展开）。
				kept = append(kept, placeholderAllNodes)
			}
			if group.Name == autoName && finalName != "" && finalName != autoName {
				// 自动选择追加「节点选择」：客户端可将自动选择手动固定到
				// 节点选择，进而在节点选择里强制全部分流走统一节点。
				kept = append(kept, finalName)
			}
			options = kept
		} else {
			options = appendDirectReject(options)
			options = append(options, placeholderAllNodes)
			if autoName != "" {
				options = append(options, autoName)
			}
			if finalName != "" {
				options = append(options, finalName)
			}
		}
		group.Options = uniqueStrings(options)
	}
	pruneWarnings, err := pruneEmptyGroups(policy, all)
	warnings = append(warnings, pruneWarnings...)
	if err != nil {
		return warnings, err
	}
	if err := detectGroupCycle(policy.Groups); err != nil {
		return warnings, err
	}
	return warnings, nil
}

// detectGroupCycle 检查组间引用环：含叶子的环（A↔B 且 B 另引节点）不会被
// pruneEmptyGroups 清除，但 Mihomo 启动校验会拒绝整份配置，发布前报错。
func detectGroupCycle(groups []policyGroup) error {
	names := make(map[string]bool, len(groups))
	for _, group := range groups {
		names[group.Name] = true
	}
	adj := make(map[string][]string, len(groups))
	for _, group := range groups {
		for _, option := range group.Options {
			if names[option] {
				adj[group.Name] = append(adj[group.Name], option)
			}
		}
	}
	const (
		white = 0 // 未访问
		gray  = 1 // 在栈中
		black = 2 // 已完成
	)
	state := map[string]int{}
	var stack []string
	var visit func(name string) error
	visit = func(name string) error {
		state[name] = gray
		stack = append(stack, name)
		for _, next := range adj[name] {
			if state[next] == gray {
				return fmt.Errorf("策略组存在循环引用：%s → %s", strings.Join(stack, " → "), next)
			}
			if state[next] == white {
				if err := visit(next); err != nil {
					return err
				}
			}
		}
		stack = stack[:len(stack)-1]
		state[name] = black
		return nil
	}
	for _, group := range groups {
		if state[group.Name] == white {
			if err := visit(group.Name); err != nil {
				return err
			}
		}
	}
	return nil
}

// sourcePolicyGroups 生成按节点来源划分的策略组：「<panelShort> 分组」包含全部面板
// 管理节点；每个外部订阅一组（组名 = 订阅名，按首次出现排序）包含其解析出的节点。
// 无节点的来源不生成组。
func sourcePolicyGroups(nodes []compiledNode, panelShort string) []policyGroup {
	var panel []string
	outerOrder := []string{}
	outer := map[string][]string{}
	for _, node := range nodes {
		if node.Group == "" {
			panel = append(panel, node.Name)
			continue
		}
		if _, ok := outer[node.Group]; !ok {
			outerOrder = append(outerOrder, node.Group)
		}
		outer[node.Group] = append(outer[node.Group], node.Name)
	}
	groups := make([]policyGroup, 0, len(outerOrder)+1)
	if len(panel) > 0 {
		groups = append(groups, policyGroup{Name: panelShort + " 分组", Type: "select", Options: panel, Source: "panel"})
	}
	for _, name := range outerOrder {
		groups = append(groups, policyGroup{Name: name, Type: "select", Options: outer[name], Source: "outer"})
	}
	return groups
}

// pruneEmptyGroups 删除展开后无可选出站的策略组，并清除其余组的悬空引用：
// 区域分组（如 🇰🇷 韩国节点）在无对应国家节点时 options 为空，Mihomo/sing-box
// 会因空组或悬空引用拒绝整份配置。规则若指向被剪除的组则跳过并给出警告。
// 无任何节点时跳过剪除（订阅本身退化为空配置，维持既有发布契约）。
// 选项级占位符按 policy.expansion 的解析结果判断存活性：解析为空的占位符
// （如没有对应国家节点的 __LATTIX_REGION_XX__）视同不存在，最终渲染展开时
// 自然消失；占位符本身在过滤阶段保留，留待最终渲染展开。
func pruneEmptyGroups(policy *portablePolicy, all []string) ([]string, error) {
	if len(all) == 0 {
		return nil, nil
	}
	nodeSet := make(map[string]bool, len(all))
	for _, name := range all {
		nodeSet[name] = true
	}
	expansion := policy.expansion
	alive := map[string]bool{}
	// optionAlive 判定选项存活：内置出站、真实节点、已存活的组引用，
	// 或解析结果非空的选项级占位符。
	optionAlive := func(option string) bool {
		if option == "DIRECT" || option == "REJECT" || nodeSet[option] || alive[option] {
			return true
		}
		return expansion != nil && isOptionPlaceholder(option) && len(expansion.resolveOption(option)) > 0
	}
	for {
		changed := false
		for _, group := range policy.Groups {
			if alive[group.Name] {
				continue
			}
			for _, option := range group.Options {
				if optionAlive(option) {
					alive[group.Name] = true
					changed = true
					break
				}
			}
		}
		if !changed {
			break
		}
	}
	if len(alive) == len(policy.Groups) {
		if policy.Final == "DIRECT" || policy.Final == "REJECT" || alive[policy.Final] {
			return nil, nil
		}
	}
	var warnings []string
	kept := policy.Groups[:0]
	for _, group := range policy.Groups {
		if !alive[group.Name] {
			warnings = append(warnings, fmt.Sprintf("策略组「%s」无可用节点或引用，已从订阅移除", group.Name))
			continue
		}
		options := make([]string, 0, len(group.Options))
		for _, option := range group.Options {
			if optionAlive(option) || isOptionPlaceholder(option) && expansion != nil && len(expansion.resolveOption(option)) == 0 {
				// 存活选项保留；解析为空的占位符也暂时保留——最终渲染展开时自然消失，
				// 避免中间态丢失模板意图。
				options = append(options, option)
			}
		}
		group.Options = options
		kept = append(kept, group)
	}
	policy.Groups = kept

	keptRules := policy.Rules[:0]
	for _, rule := range policy.Rules {
		if rule.Outbound != "DIRECT" && rule.Outbound != "REJECT" && !alive[rule.Outbound] {
			warnings = append(warnings, fmt.Sprintf("规则 %s,%s 指向已移除的策略组「%s」，已跳过", rule.Kind, rule.Value, rule.Outbound))
			continue
		}
		keptRules = append(keptRules, rule)
	}
	policy.Rules = keptRules

	keptRemote := policy.RemoteRule[:0]
	for _, remote := range policy.RemoteRule {
		if remote.Outbound != "DIRECT" && remote.Outbound != "REJECT" && !alive[remote.Outbound] {
			warnings = append(warnings, fmt.Sprintf("远程规则 %s 指向已移除的策略组「%s」，已跳过", remote.Name, remote.Outbound))
			continue
		}
		keptRemote = append(keptRemote, remote)
	}
	policy.RemoteRule = keptRemote

	if policy.Final != "DIRECT" && policy.Final != "REJECT" && !alive[policy.Final] {
		return warnings, fmt.Errorf("final 指向已移除的策略组 %q", policy.Final)
	}
	return warnings, nil
}

// noRegionGroupName 是无地区标识节点的固定分组名：随地区分组一起生成并排在最后，
// 同时随 __LATTIX_REGIONS__ 展开，保证无国家代码的节点在分组层也可达。
const noRegionGroupName = "🌐 无地区"

func countryFlag(code string) string {
	if len(code) != 2 {
		return "🌐"
	}
	runes := []rune(strings.ToUpper(code))
	return string([]rune{runes[0] - 'A' + 0x1F1E6, runes[1] - 'A' + 0x1F1E6})
}

func uniqueStrings(values []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

// mihomoPre 是 clash 订阅的预编译中间态：节点区与来源分组区以占位符表示，
// 组选项中的选项级占位符（__LATTIX_ALL__ 等）同样保留到最终渲染才展开；
// 规则/DNS/geodata 等已就绪；expand 解压为最终配置，artifact 输出中间态 YAML。
type mihomoPre struct {
	config      clashConfig // Proxies/ProxyGroups 为空，其余字段已填
	proxies     []any       // 节点占位符
	groups      []any       // policyGroup 或来源分组占位符
	panelGroup  *policyGroup
	outerGroups []policyGroup
	expansion   *policyExpansion // 选项级占位符的最终展开上下文
}

func renderMihomoPre(policy portablePolicy) mihomoPre {
	pre := mihomoPre{
		config:    clashConfig{Proxies: []clashProxy{}, RuleProviders: map[string]clashRuleProvider{}},
		proxies:   []any{placeholderLattixNodes, placeholderOuterSubsNodes},
		expansion: policy.expansion,
	}
	pre.config.DNS = defaultClashDNS()
	panelDone, outerDone := false, false
	for _, group := range policy.Groups {
		switch group.Source {
		case "panel":
			if !panelDone {
				pre.groups = append(pre.groups, placeholderLattixGroup)
				panelDone = true
			}
			g := group
			pre.panelGroup = &g
		case "outer":
			if !outerDone {
				pre.groups = append(pre.groups, placeholderOuterSubsGroup)
				outerDone = true
			}
			pre.outerGroups = append(pre.outerGroups, group)
		default:
			pre.groups = append(pre.groups, group)
		}
	}
	needsGeodata := false
	for _, rule := range policy.Rules {
		pre.config.Rules = append(pre.config.Rules, fmt.Sprintf("%s,%s,%s", rule.Kind, rule.Value, rule.Outbound))
		if rule.Kind == "GEOSITE" || rule.Kind == "GEOIP" {
			needsGeodata = true
		}
	}
	for _, remote := range policy.RemoteRule {
		pre.config.RuleProviders[remote.Name] = clashRuleProvider{
			Type: "http", Behavior: remote.Behavior, URL: remote.URL,
			Path: "./ruleset/" + remote.Name + ".yaml", Interval: 21600,
		}
		pre.config.Rules = append(pre.config.Rules, "RULE-SET,"+remote.Name+","+remote.Outbound)
	}
	pre.config.Rules = append(pre.config.Rules, "MATCH,"+policy.Final)
	if needsGeodata {
		pre.config.GeodataMode = true
		pre.config.GeoAutoUpdate = true
		pre.config.GeodataLoader = "standard"
		pre.config.GeoUpdateInterval = 24
		pre.config.GeoXURL = &clashGeoxURL{
			Geoip:   "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat",
			Geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat",
			MMDB:    "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.mmdb",
			ASN:     "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb",
		}
	}
	return pre
}

// expand 解压中间态：节点占位符替换为真实节点，来源分组占位符替换为构建期
// 捕获的分组载荷，选项级占位符按 expansion 展开为真实节点/分组名；
// 空来源（无面板节点/无外部订阅）的占位符条目被删除。
func (p mihomoPre) expand(nodes []compiledNode) clashConfig {
	panel, outer := splitNodesBySource(nodes)
	out := p.config
	out.Proxies = []clashProxy{}
	for _, entry := range p.proxies {
		switch entry {
		case placeholderLattixNodes:
			for _, node := range panel {
				out.Proxies = append(out.Proxies, node.Clash)
			}
		case placeholderOuterSubsNodes:
			for _, node := range outer {
				out.Proxies = append(out.Proxies, node.Clash)
			}
		}
	}
	out.ProxyGroups = []clashProxyGroup{}
	appendGroup := func(group policyGroup) {
		out.ProxyGroups = append(out.ProxyGroups, clashProxyGroup{
			Name: group.Name, Type: group.Type, Proxies: expandPolicyOptions(group.Options, p.expansion),
			URL: group.URL, Interval: group.Interval, Tolerance: group.Tolerance,
		})
	}
	for _, entry := range p.groups {
		switch entry {
		case placeholderLattixGroup:
			if p.panelGroup != nil {
				appendGroup(*p.panelGroup)
			}
		case placeholderOuterSubsGroup:
			for _, group := range p.outerGroups {
				appendGroup(group)
			}
		default:
			appendGroup(entry.(policyGroup))
		}
	}
	return out
}

// groupMaps 把中间态分组列表转为 map 序列（占位符字符串保留、组选项不展开），
// 供原生模板缺省分组区与中间态 artifact 使用。
func (p mihomoPre) groupMaps() ([]any, error) {
	groups := make([]any, 0, len(p.groups))
	for _, entry := range p.groups {
		group, ok := entry.(policyGroup)
		if !ok {
			groups = append(groups, entry)
			continue
		}
		var m map[string]any
		raw, err := yaml.Marshal(clashProxyGroup{
			Name: group.Name, Type: group.Type, Proxies: group.Options,
			URL: group.URL, Interval: group.Interval, Tolerance: group.Tolerance,
		})
		if err != nil {
			return nil, err
		}
		if err := yaml.Unmarshal(raw, &m); err != nil {
			return nil, err
		}
		groups = append(groups, m)
	}
	return groups, nil
}

// artifact 输出中间态 YAML（占位符保留），供调试预览与排查分组问题。
func (p mihomoPre) artifact() ([]byte, error) {
	var doc map[string]any
	body, err := yaml.Marshal(p.config)
	if err != nil {
		return nil, err
	}
	if err := yaml.Unmarshal(body, &doc); err != nil {
		return nil, err
	}
	doc["proxies"] = p.proxies
	groups, err := p.groupMaps()
	if err != nil {
		return nil, err
	}
	doc["proxy-groups"] = groups
	return yaml.Marshal(doc)
}

func renderMihomo(policy portablePolicy, nodes []compiledNode) ([]byte, error) {
	pre := renderMihomoPre(policy)
	body, err := yaml.Marshal(pre.expand(nodes))
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by Lattix. Template source and license are recorded in the panel.\n"), body...), nil
}

// defaultClashDNS 返回内置 fake-ip DNS 配置，使 GEOSITE/GEOIP 与 RULE-SET 规则
// 在客户端无需额外配置即可生效。节点域名（如 hk.whoisbean.com）经
// proxy-server-nameserver 用国内可达解析器直查，不经过境外交互，避免节点测速/连接超时。
func defaultClashDNS() *clashDNS {
	return &clashDNS{
		Enable:       true,
		IPv6:         false,
		EnhancedMode: "fake-ip",
		FakeIPRange:  "198.18.0.1/16",
		FakeIPFilter: []string{
			"*.lan", "*.localdomain", "*.example", "*.invalid", "*.local",
			"*.home.arpa", "time.*.com", "ntp.*.com", "+.pool.ntp.org", "+.mcdn.bilivideo.cn",
		},
		DefaultNameserver:     []string{"223.5.5.5", "119.29.29.29"},
		Nameserver:            []string{"https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"},
		ProxyServerNameserver: []string{"https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"},
	}
}

// singboxGroupType 把便携策略组类型映射为 sing-box outbound 类型。
func singboxGroupType(typeName string) string {
	switch typeName {
	case "select":
		return "selector"
	case "url-test":
		return "urltest"
	case "fallback", "load-balance":
		return "selector"
	default:
		return typeName
	}
}

func singboxGroupOutbound(group policyGroup) map[string]any {
	return map[string]any{"type": singboxGroupType(group.Type), "tag": group.Name, "outbounds": group.Options}
}

// singboxPre 是 sing-box 订阅的预编译中间态：outbounds 中节点区与来源分组区
// 以占位符表示，组选项中的选项级占位符保留到最终渲染才展开；
// expand 解压为最终配置，artifact 输出中间态 JSON。
type singboxPre struct {
	route       map[string]any
	outbounds   []any // 节点占位符 + DIRECT/REJECT + policyGroup 或来源分组占位符
	panelGroup  *policyGroup
	outerGroups []policyGroup
	expansion   *policyExpansion
}

func renderSingboxPre(policy portablePolicy) singboxPre {
	pre := singboxPre{
		outbounds: []any{
			placeholderLattixNodes, placeholderOuterSubsNodes,
			map[string]any{"type": "direct", "tag": "DIRECT"},
			map[string]any{"type": "block", "tag": "REJECT"},
		},
		expansion: policy.expansion,
	}
	panelDone, outerDone := false, false
	for _, group := range policy.Groups {
		switch group.Source {
		case "panel":
			if !panelDone {
				pre.outbounds = append(pre.outbounds, placeholderLattixGroup)
				panelDone = true
			}
			g := group
			pre.panelGroup = &g
		case "outer":
			if !outerDone {
				pre.outbounds = append(pre.outbounds, placeholderOuterSubsGroup)
				outerDone = true
			}
			pre.outerGroups = append(pre.outerGroups, group)
		default:
			pre.outbounds = append(pre.outbounds, group)
		}
	}
	rules := make([]any, 0, len(policy.Rules)+len(policy.RemoteRule))
	for _, rule := range policy.Rules {
		entry := map[string]any{"outbound": rule.Outbound}
		if rule.Kind == "GEOSITE" {
			entry["geosite"] = []string{rule.Value}
		} else if rule.Kind == "GEOIP" {
			entry["geoip"] = []string{strings.ToLower(rule.Value)}
		}
		rules = append(rules, entry)
	}
	ruleSets := make([]any, 0, len(policy.RemoteRule))
	for _, remote := range policy.RemoteRule {
		ruleSets = append(ruleSets, map[string]any{
			"type": "remote", "tag": remote.Name, "format": "source", "url": remote.URL,
			"download_detour": "DIRECT", "update_interval": "6h",
		})
		rules = append(rules, map[string]any{"rule_set": []string{remote.Name}, "outbound": remote.Outbound})
	}
	pre.route = map[string]any{"rules": rules, "rule_set": ruleSets, "final": policy.Final}
	return pre
}

// expand 解压中间态：节点占位符替换为真实 outbound（Singbox 为空的节点跳过），
// 来源分组占位符替换为构建期捕获的组载荷，选项级占位符按 expansion 展开；
// 空来源的占位符条目被删除。
func (p singboxPre) expand(nodes []compiledNode) map[string]any {
	panel, outer := splitNodesBySource(nodes)
	appendNodes := func(out []any, source []compiledNode) []any {
		for _, node := range source {
			if node.Singbox == nil {
				continue
			}
			out = append(out, node.Singbox)
		}
		return out
	}
	appendGroup := func(out []any, group policyGroup) []any {
		group.Options = expandPolicyOptions(group.Options, p.expansion)
		return append(out, singboxGroupOutbound(group))
	}
	outbounds := make([]any, 0, len(p.outbounds)+len(nodes))
	for _, entry := range p.outbounds {
		switch entry {
		case placeholderLattixNodes:
			outbounds = appendNodes(outbounds, panel)
		case placeholderOuterSubsNodes:
			outbounds = appendNodes(outbounds, outer)
		case placeholderLattixGroup:
			if p.panelGroup != nil {
				outbounds = appendGroup(outbounds, *p.panelGroup)
			}
		case placeholderOuterSubsGroup:
			for _, group := range p.outerGroups {
				outbounds = appendGroup(outbounds, group)
			}
		default:
			if group, ok := entry.(policyGroup); ok {
				outbounds = appendGroup(outbounds, group)
				continue
			}
			outbounds = append(outbounds, entry)
		}
	}
	return map[string]any{"outbounds": outbounds, "route": p.route}
}

// artifact 输出中间态 JSON（占位符保留、组选项不展开），供调试预览与排查分组问题。
func (p singboxPre) artifact() ([]byte, error) {
	outbounds := make([]any, 0, len(p.outbounds))
	for _, entry := range p.outbounds {
		if group, ok := entry.(policyGroup); ok {
			outbounds = append(outbounds, singboxGroupOutbound(group))
			continue
		}
		outbounds = append(outbounds, entry)
	}
	return json.MarshalIndent(map[string]any{"outbounds": outbounds, "route": p.route}, "", "  ")
}

func renderSingbox(policy portablePolicy, nodes []compiledNode) ([]byte, error) {
	pre := renderSingboxPre(policy)
	return json.MarshalIndent(pre.expand(nodes), "", "  ")
}

// quanxNodeLines 返回节点的 QuanX server 行（跳过无 QuanX 行的节点）。
func quanxNodeLines(nodes []compiledNode) []string {
	lines := make([]string, 0, len(nodes))
	for _, node := range nodes {
		if node.QuanX != "" {
			lines = append(lines, node.QuanX)
		}
	}
	return lines
}

// renderQuanXNodesPre 返回 quanx 节点区的预编译中间态（两行节点占位符）。
func renderQuanXNodesPre() string {
	return placeholderLattixNodes + "\n" + placeholderOuterSubsNodes + "\n"
}

// expandQuanXNodes 解压节点占位符为真实 server 行。
func expandQuanXNodes(pre string, nodes []compiledNode) string {
	panel, outer := splitNodesBySource(nodes)
	return expandTextPlaceholders(pre, map[string][]string{
		placeholderLattixNodes:    quanxNodeLines(panel),
		placeholderOuterSubsNodes: quanxNodeLines(outer),
	})
}

func renderQuanXNodes(nodes []compiledNode) string {
	return expandQuanXNodes(renderQuanXNodesPre(), nodes)
}

// quanxPolicyLine 渲染一行 [policy] 组定义。
func quanxPolicyLine(group policyGroup) string {
	mode := "static"
	if group.Type == "url-test" {
		mode = "url-latency-benchmark"
	}
	return mode + "=" + group.Name + ", " + strings.Join(group.Options, ", ")
}

// quanxConfigPre 是 quanx-config 的预编译中间态：[server_local] 含节点占位符行，
// 组列表单独保存（含来源分组占位符），组选项中的选项级占位符保留到最终渲染
// 才展开；expand 解压为最终配置。
type quanxConfigPre struct {
	prefix      string // 到 [policy] 头为止（含节点占位符行）
	groups      []any  // policyGroup 或来源分组占位符
	suffix      string // [filter_remote] 起的尾部
	panelGroup  *policyGroup
	outerGroups []policyGroup
	expansion   *policyExpansion
}

func renderQuanXConfigPre(policy portablePolicy) quanxConfigPre {
	pre := quanxConfigPre{expansion: policy.expansion}
	var head strings.Builder
	head.WriteString("# Generated by Lattix\n[server_local]\n")
	head.WriteString(renderQuanXNodesPre())
	head.WriteString("\n[policy]\n")
	pre.prefix = head.String()
	panelDone, outerDone := false, false
	for _, group := range policy.Groups {
		switch group.Source {
		case "panel":
			if !panelDone {
				pre.groups = append(pre.groups, placeholderLattixGroup)
				panelDone = true
			}
			g := group
			pre.panelGroup = &g
		case "outer":
			if !outerDone {
				pre.groups = append(pre.groups, placeholderOuterSubsGroup)
				outerDone = true
			}
			pre.outerGroups = append(pre.outerGroups, group)
		default:
			pre.groups = append(pre.groups, group)
		}
	}
	var tail strings.Builder
	tail.WriteString("\n[filter_remote]\n")
	for _, remote := range policy.RemoteRule {
		tail.WriteString(remote.URL + ", tag=" + remote.Name + ", force-policy=" + remote.Outbound + ", enabled=true\n")
	}
	tail.WriteString("\n[filter_local]\n")
	for _, rule := range policy.Rules {
		tail.WriteString(rule.Kind + "," + rule.Value + "," + rule.Outbound + "\n")
	}
	tail.WriteString("FINAL," + policy.Final + "\n")
	pre.suffix = tail.String()
	return pre
}

// policyLines 渲染组记录行：来源分组占位符替换为构建期捕获的组行，选项级
// 占位符按 expansion 展开；空来源的占位符行被删除。expanded 控制是否展开选项。
func (p quanxConfigPre) policyLines(expanded bool) []string {
	lines := make([]string, 0, len(p.groups))
	appendGroup := func(group policyGroup) {
		if expanded {
			group.Options = expandPolicyOptions(group.Options, p.expansion)
		}
		lines = append(lines, quanxPolicyLine(group))
	}
	for _, entry := range p.groups {
		switch entry {
		case placeholderLattixGroup:
			if !expanded {
				lines = append(lines, entry.(string))
			} else if p.panelGroup != nil {
				appendGroup(*p.panelGroup)
			}
		case placeholderOuterSubsGroup:
			if !expanded {
				lines = append(lines, entry.(string))
			} else {
				for _, group := range p.outerGroups {
					appendGroup(group)
				}
			}
		default:
			appendGroup(entry.(policyGroup))
		}
	}
	return lines
}

// expand 解压中间态：节点占位符行替换为真实 server 行，组行渲染并展开选项。
func (p quanxConfigPre) expand(nodes []compiledNode) []byte {
	text := expandQuanXNodes(p.prefix, nodes)
	for _, line := range p.policyLines(true) {
		text += line + "\n"
	}
	return []byte(text + p.suffix)
}

// artifact 输出中间态文本（占位符保留、组选项不展开），供调试预览。
func (p quanxConfigPre) artifact() []byte {
	text := p.prefix
	for _, line := range p.policyLines(false) {
		text += line + "\n"
	}
	return []byte(text + p.suffix)
}

func renderQuanXConfig(policy portablePolicy, nodes []compiledNode) ([]byte, error) {
	pre := renderQuanXConfigPre(policy)
	return pre.expand(nodes), nil
}

// linksPre 是 links 订阅的预编译中间态：占位符行 + 构建期捕获的分享链接载荷。
type linksPre struct {
	text       string
	panelLinks []string
	outerLinks []string
}

func renderLinksPre(items []proxyItem, uuid string) linksPre {
	pre := linksPre{text: placeholderLattixNodes + "\n" + placeholderOuterSubsNodes + "\n"}
	for _, item := range items {
		if item.external != nil {
			if link, ok := buildExternalLink(*item.external); ok {
				pre.outerLinks = append(pre.outerLinks, link)
			}
			continue
		}
		credential := item.credential
		if credential == "" {
			credential = uuid
		}
		if link, ok := buildShareLink(item.node, item.rc, credential); ok {
			pre.panelLinks = append(pre.panelLinks, link)
		}
	}
	return pre
}

// expand 解压中间态：占位符行替换为真实分享链接后 base64 编码交付。
func (p linksPre) expand() []byte {
	body := expandTextPlaceholders(p.text, map[string][]string{
		placeholderLattixNodes:    p.panelLinks,
		placeholderOuterSubsNodes: p.outerLinks,
	})
	encoded := base64.StdEncoding.EncodeToString([]byte(strings.TrimRight(body, "\n")))
	return []byte(encoded + "\n")
}

// artifact 输出中间态文本（占位符保留），供调试预览。
func (p linksPre) artifact() []byte { return []byte(p.text) }

func renderLinks(items []proxyItem, uuid string) ([]byte, error) {
	return renderLinksPre(items, uuid).expand(), nil
}

// clashNodeMaps 把节点 clashProxy 载荷经 yaml round-trip 转为 map（Raw 内联
// 键随之展开保留），作为原生模板节点占位符的解压载荷。
func clashNodeMaps(list []compiledNode) ([]any, error) {
	out := make([]any, 0, len(list))
	for _, node := range list {
		raw, err := yaml.Marshal(node.Clash)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := yaml.Unmarshal(raw, &m); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, nil
}

// nativeSourceGroupMaps 构造来源分组的解压载荷（与 expandNativeGroupsPre 的
// 占位符语义对应）；与既有组重名的来源分组跳过。
func nativeSourceGroupMaps(nodes []compiledNode, nameKey, regionType, optionKey, panelShort string, existing map[string]bool) (panel []any, outer []any) {
	groupMap := func(group policyGroup) map[string]any {
		values := make([]any, 0, len(group.Options))
		for _, option := range group.Options {
			values = append(values, option)
		}
		return map[string]any{nameKey: group.Name, "type": regionType, optionKey: values}
	}
	for _, group := range sourcePolicyGroups(nodes, panelShort) {
		if existing[group.Name] {
			continue
		}
		existing[group.Name] = true
		if group.Source == "panel" {
			panel = append(panel, groupMap(group))
		} else {
			outer = append(outer, groupMap(group))
		}
	}
	return panel, outer
}

// applyNativeTemplate 应用原生模板并返回最终交付内容（占位符已全部解压）。
func applyNativeTemplate(format, content string, policy portablePolicy, nodes []compiledNode, panelShort string) ([]byte, error) {
	_, final, err := applyNativeTemplateFull(format, content, policy, nodes, panelShort)
	return final, err
}

// applyNativeTemplateFull 应用原生模板，返回预编译中间态与最终交付内容。
// 模板可手写条目级占位符控制注入位置：节点区 __LATTIX-NODES__ /
// __OUTTER-SUBS-NODES__，分组区 __LATTIX-GROUP__ / __OUTER-SUBS-GROUP__；
// 未写时按默认规则注入（节点区整体替换/前置，来源分组追加在模板分组之后）。
func applyNativeTemplateFull(format, content string, policy portablePolicy, nodes []compiledNode, panelShort string) (pre, final []byte, err error) {
	switch format {
	case "clash":
		var document map[string]any
		if err := yaml.Unmarshal([]byte(content), &document); err != nil {
			return nil, nil, fmt.Errorf("parse Mihomo native template: %w", err)
		}
		generated, err := renderMihomo(policy, nodes)
		if err != nil {
			return nil, nil, err
		}
		var values map[string]any
		if err := yaml.Unmarshal(generated, &values); err != nil {
			return nil, nil, err
		}
		panel, outer := splitNodesBySource(nodes)
		panelMaps, err := clashNodeMaps(panel)
		if err != nil {
			return nil, nil, err
		}
		outerMaps, err := clashNodeMaps(outer)
		if err != nil {
			return nil, nil, err
		}
		nodePayload := map[string][]any{
			placeholderLattixNodes:    panelMaps,
			placeholderOuterSubsNodes: outerMaps,
		}
		if proxies, ok := document["proxies"].([]any); ok && containsEntryPlaceholder(proxies, placeholderLattixNodes, placeholderOuterSubsNodes) {
			// 模板手写节点占位符：保留位置，中间态原样呈现。
		} else {
			document["proxies"] = []any{placeholderLattixNodes, placeholderOuterSubsNodes}
		}
		if groups, ok := document["proxy-groups"].([]any); ok {
			document["proxy-groups"] = expandNativeGroupsPre(groups, "proxies", nodes, "name", "select", panelShort)
		} else {
			pre := renderMihomoPre(policy)
			document["proxy-groups"], err = pre.groupMaps()
			if err != nil {
				return nil, nil, err
			}
		}
		if _, ok := document["rules"]; !ok {
			document["rules"] = values["rules"]
		}
		pre, err = yaml.Marshal(document)
		if err != nil {
			return nil, nil, err
		}
		document["proxies"] = spliceEntryPlaceholders(document["proxies"].([]any), nodePayload)
		document["proxy-groups"] = materializeNativeGroups(document["proxy-groups"].([]any), "proxies", nodes, "name", "select", panelShort)
		final, err = yaml.Marshal(document)
		return pre, final, err
	case "singbox":
		var document map[string]any
		if err := json.Unmarshal([]byte(content), &document); err != nil {
			return nil, nil, fmt.Errorf("parse sing-box native template: %w", err)
		}
		generated, err := renderSingbox(policy, nodes)
		if err != nil {
			return nil, nil, err
		}
		var values map[string]any
		if err := json.Unmarshal(generated, &values); err != nil {
			return nil, nil, err
		}
		panel, outer := splitNodesBySource(nodes)
		singboxOutbounds := func(list []compiledNode) []any {
			out := make([]any, 0, len(list))
			for _, node := range list {
				if node.Singbox != nil {
					out = append(out, node.Singbox)
				}
			}
			return out
		}
		nodePayload := map[string][]any{
			placeholderLattixNodes:    singboxOutbounds(panel),
			placeholderOuterSubsNodes: singboxOutbounds(outer),
		}
		if outbounds, ok := document["outbounds"].([]any); ok {
			if containsEntryPlaceholder(outbounds, placeholderLattixNodes, placeholderOuterSubsNodes) {
				// 模板手写节点占位符：保留位置，仅确保 DIRECT/REJECT 存在。
				outbounds = ensureSingboxDirectReject(outbounds)
			} else {
				injected := []any{
					placeholderLattixNodes, placeholderOuterSubsNodes,
					map[string]any{"type": "direct", "tag": "DIRECT"},
					map[string]any{"type": "block", "tag": "REJECT"},
				}
				outbounds = append(injected, expandNativeGroupsPre(outbounds, "outbounds", nodes, "tag", "selector", panelShort)...)
			}
			document["outbounds"] = outbounds
		} else {
			document["outbounds"] = renderSingboxPre(policy).outbounds
		}
		if _, ok := document["route"]; !ok {
			document["route"] = values["route"]
		}
		pre, err = json.MarshalIndent(document, "", "  ")
		if err != nil {
			return nil, nil, err
		}
		outbounds := document["outbounds"].([]any)
		outbounds = spliceEntryPlaceholders(outbounds, nodePayload)
		outbounds = materializeNativeGroups(outbounds, "outbounds", nodes, "tag", "selector", panelShort)
		document["outbounds"] = uniqueNativeGroups(outbounds, "tag")
		final, err = json.MarshalIndent(document, "", "  ")
		return pre, final, err
	case "quanx-config":
		// QuanX 原生模板即中间态：__LATTIX_SERVERS__ 为兼容写法（= 两类节点
		// 合并），新占位符 __LATTIX-NODES__ / __OUTTER-SUBS-NODES__ 按来源拆分。
		if !strings.Contains(content, "__LATTIX_SERVERS__") &&
			!strings.Contains(content, placeholderLattixNodes) &&
			!strings.Contains(content, placeholderOuterSubsNodes) {
			return nil, nil, errors.New("Quantumult X native template requires __LATTIX_SERVERS__")
		}
		panel, outer := splitNodesBySource(nodes)
		servers := strings.Join(quanxNodeLines(nodes), "\n")
		text := strings.ReplaceAll(content, "__LATTIX_SERVERS__", servers)
		replacements := map[string][]string{
			placeholderLattixNodes:    quanxNodeLines(panel),
			placeholderOuterSubsNodes: quanxNodeLines(outer),
		}
		var panelLines, outerLines []string
		for _, group := range sourcePolicyGroups(nodes, panelShort) {
			if group.Source == "panel" {
				panelLines = append(panelLines, quanxPolicyLine(group))
			} else {
				outerLines = append(outerLines, quanxPolicyLine(group))
			}
		}
		replacements[placeholderLattixGroup] = panelLines
		replacements[placeholderOuterSubsGroup] = outerLines
		return []byte(content), []byte(expandTextPlaceholders(text, replacements)), nil
	default:
		return nil, nil, fmt.Errorf("unsupported native template format %q", format)
	}
}

// ensureSingboxDirectReject 确保 outbounds 含 DIRECT/REJECT 出口（缺失时前置补齐）。
func ensureSingboxDirectReject(outbounds []any) []any {
	has := map[string]bool{}
	for _, entry := range outbounds {
		if m, ok := entry.(map[string]any); ok {
			if tag, _ := m["tag"].(string); tag == "DIRECT" || tag == "REJECT" {
				has[tag] = true
			}
		}
	}
	prefix := []any{}
	if !has["DIRECT"] {
		prefix = append(prefix, map[string]any{"type": "direct", "tag": "DIRECT"})
	}
	if !has["REJECT"] {
		prefix = append(prefix, map[string]any{"type": "block", "tag": "REJECT"})
	}
	return append(prefix, outbounds...)
}

func uniqueNativeGroups(groups []any, nameKey string) []any {
	seen := map[string]bool{}
	out := make([]any, 0, len(groups))
	for _, value := range groups {
		group, ok := value.(map[string]any)
		if !ok {
			out = append(out, value)
			continue
		}
		name, _ := group[nameKey].(string)
		if name != "" && seen[name] {
			continue
		}
		seen[name] = name != ""
		out = append(out, group)
	}
	return out
}

// expandNativeGroupsPre 处理原生模板分组区：来源分组以条目占位符
// （__LATTIX-GROUP__ / __OUTER-SUBS-GROUP__）表示——模板手写占位符时保留原位，
// 否则按默认位置（模板分组之后）补占位符；地区分组以实体条目追加，选项为
// 单地区占位符 __LATTIX_REGION_XX__（无地区分组为 __LATTIX_REGION_NONE__）。
// 模板组选项中的选项级占位符在中间态保持原样，到 materializeNativeGroups
// 才展开为真实节点/分组名。
func expandNativeGroupsPre(groups []any, optionKey string, nodes []compiledNode, nameKey, regionType, panelShort string) []any {
	_, regions, _ := nativeNodeOptions(nodes)
	expanded := make([]any, 0, len(groups)+len(regions)+2)
	existing := map[string]bool{}
	lattixSeen, outerSeen := false, false
	for _, value := range groups {
		if s, ok := value.(string); ok {
			switch s {
			case placeholderLattixGroup:
				lattixSeen = true
			case placeholderOuterSubsGroup:
				outerSeen = true
			}
			expanded = append(expanded, value)
			continue
		}
		if group, ok := value.(map[string]any); ok {
			if name, _ := group[nameKey].(string); name != "" {
				existing[name] = true
			}
		}
		expanded = append(expanded, value)
	}
	// 模板未手写来源分组占位符时按默认位置补（与既有组重名的来源不补，
	// 避免解压出重复组名）。
	var panelName string
	outerPending := false
	for _, group := range sourcePolicyGroups(nodes, panelShort) {
		if group.Source == "panel" {
			panelName = group.Name
		} else if !existing[group.Name] {
			outerPending = true
		}
	}
	if !lattixSeen && panelName != "" && !existing[panelName] {
		expanded = append(expanded, placeholderLattixGroup)
	}
	if !outerSeen && outerPending {
		expanded = append(expanded, placeholderOuterSubsGroup)
	}
	for _, region := range regions {
		if existing[region] {
			continue
		}
		existing[region] = true
		option := placeholderRegionNone
		if region != noRegionGroupName {
			code := region[strings.LastIndex(region, " ")+1:]
			option = placeholderRegionPrefix + code + "__"
		}
		expanded = append(expanded, map[string]any{nameKey: region, "type": regionType, optionKey: []any{option}})
	}
	return expanded
}

// materializeNativeGroups 把中间态分组列表解压为最终分组条目：所有组选项中的
// 选项级占位符（__LATTIX_ALL__ / __LATTIX_REGIONS__ / __LATTIX_REGION_XX__ /
// __LATTIX_REGION_NONE__）展开为真实节点/分组名，来源分组占位符解压为真实
// 分组条目；与既有组重名的来源分组跳过（与 expandNativeGroupsPre 语义一致）。
func materializeNativeGroups(groups []any, optionKey string, nodes []compiledNode, nameKey, regionType, panelShort string) []any {
	all, regions, byCountry := nativeNodeOptions(nodes)
	// __LATTIX_REGIONS__ 展开为叶子分组：来源分组（面板分组 + 各外部订阅分组）
	// 与地区分组同级，一同出现、一同剔除。
	leafGroups := make([]string, 0, len(regions)+2)
	for _, group := range sourcePolicyGroups(nodes, panelShort) {
		leafGroups = append(leafGroups, group.Name)
	}
	leafGroups = append(leafGroups, regions...)
	existing := map[string]bool{}
	expanded := make([]any, 0, len(groups))
	for _, value := range groups {
		if group, ok := value.(map[string]any); ok {
			if name, _ := group[nameKey].(string); name != "" {
				existing[name] = true
			}
			if options, ok := group[optionKey].([]any); ok {
				group[optionKey] = expandNativeOptions(options, all, leafGroups, byCountry)
			}
		}
		expanded = append(expanded, value)
	}
	panel, outer := nativeSourceGroupMaps(nodes, nameKey, regionType, optionKey, panelShort, existing)
	return spliceEntryPlaceholders(expanded, map[string][]any{
		placeholderLattixGroup:    panel,
		placeholderOuterSubsGroup: outer,
	})
}

func nativeNodeOptions(nodes []compiledNode) ([]string, []string, map[string][]string) {
	all := make([]string, 0, len(nodes))
	byCountry := map[string][]string{}
	var noRegion []string
	for _, node := range nodes {
		all = append(all, node.Name)
		if node.CountryCode != "" {
			region := countryFlag(node.CountryCode) + " " + strings.ToUpper(node.CountryCode)
			byCountry[region] = append(byCountry[region], node.Name)
		} else {
			noRegion = append(noRegion, node.Name)
		}
	}
	regions := make([]string, 0, len(byCountry)+1)
	for region := range byCountry {
		regions = append(regions, region)
	}
	sort.Strings(regions)
	if len(noRegion) > 0 {
		byCountry[noRegionGroupName] = noRegion
		regions = append(regions, noRegionGroupName)
	}
	return all, regions, byCountry
}

func expandNativeOptions(options []any, all, regions []string, byCountry map[string][]string) []any {
	var expanded []any
	appendStrings := func(values []string) {
		for _, value := range values {
			expanded = append(expanded, value)
		}
	}
	for _, raw := range options {
		option, ok := raw.(string)
		if !ok {
			expanded = append(expanded, raw)
			continue
		}
		switch option {
		case placeholderAllNodes:
			appendStrings(all)
		case placeholderLeafGroups:
			appendStrings(regions)
		case placeholderRegionNone:
			appendStrings(byCountry[noRegionGroupName])
		default:
			if strings.HasPrefix(option, placeholderRegionPrefix) && strings.HasSuffix(option, "__") {
				country := strings.TrimSuffix(strings.TrimPrefix(option, placeholderRegionPrefix), "__")
				appendStrings(byCountry[countryFlag(country)+" "+strings.ToUpper(country)])
				continue
			}
			expanded = append(expanded, option)
		}
	}
	return expanded
}

func contentSHA(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

func nowPointer() *time.Time {
	now := time.Now().UTC()
	return &now
}
